### ISSUE TITLE
License Policy

### ISSUE THREAD

**Issue by JohanOusager** [SengerM/VotschTechnik-climate-chamber-Python#1]
Hi

I stumbled upon this great library and thought it would be useful at work.

You do not include a license policy on this page, so I wanted to reach out and ask what conditions you allow the use or modification of this software (if any).

Best regards.

**Comment by SengerM** [comment]
Dear Johan Ousager,

Thank you for your comments and for pointing that out. I added the license file. I hope you find this software package useful.

Kind regards,
Matias.
